version: '3.8'

services:
  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy:/haproxy-override
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "70:70" # haproxy admin console, login with user:pass
    networks:
      - backend-net
      - frontend-net

  dan-ui:
    image: dan-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:3000"
    networks:
      - frontend-net

networks:
  backend-net:
    external: true
  frontend-net:
    driver: bridge

volumes:
  haproxy:  # Named volume for persistence
